<?php echo $this->doctype() ?>
<html>

<head>
	
	<title>TrISS:Via la carta, non lo scontrino</title>
	
	<?= $this->headMeta();?>
	
    <?= $this->headLink();?>
	
    <?= $this->headTitle();?>
	
    <?= $this->headScript();?>
	
	<?= $this->headScript()
		->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js')
		->appendFile($this->baseUrl('js/vendor/jquery-1.11.2.min.js'))
		->appendFile($this->baseUrl('js/vendor/bootstrap.min.js'))
		->appendFile($this->baseUrl('js/jquery.easypiechart.min.js'))
		->appendFile($this->baseUrl('js/plugins.js'))
		->appendFile($this->baseUrl('js/main.js'))
		->appendFile($this->baseUrl('js/vendor/modernizr-2.8.3-respond-1.4.2.min.js'))
	?>
 
 </head>
    <body data-spy="scroll" data-target="#navmenu">
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
		<div class='preloader'><div class='loaded'>&nbsp;</div></div>
        <!--Home page style-->
        <header id="main_menu" class="header">
			 <?= $this->render('navbar.phtml') ?>
		 </header> <!--End of header -->



        <section id="home" class="home">
            <div class="home-overlay-fluid">
                <div class="container">
                    <div class="row">
                        <div class="main_slider_area">
                            <div class="slider">
                                <div class="single_slider wow fadeIn" data-wow-duration="2s">
                                    <?php echo $this->layout()->content; ?>
                                </div>


        <section id="footer" class="footer sections">
            <div class="container">
                <div class="row">
                    <div class="main_footer wow fadeInDown" data-wow-duration="2s">
                        <div class="col-sm-3 col-xs-12">
                            <div class="footer_logo">
                            </div>
                        </div>
                        <div class="col-sm-9 col-xs-12">
                            <div class="footer_menu">
                                <ul class="list-inline">
                                    <li><a href="">ABOUT US</a></li>
                                    <li><a href="">BLOG</a></li>
                                    <li><a href="">POLICY</a></li>
                                    <li><a href="">CONTACT</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="footer_bottom_area">
                        <div class="col-sm-9 col-xs-12">
                            <div class="fo_bottom_right">
                                <div class="row">
                                    <div class="col-sm-6 col-xs-12">
                                        <div class="single_right_footer wow fadeIn" data-wow-duration="1s">
                                            <p>Via la carta, non lo scontrino</p>
                                            <a href="">Gruppo : <strong>L'Hackompagnia dell'anello</strong></a>
											
                                        </div>
                                    </div>
                                    <div class="col-sm-3 col-xs-6">
                                        <div class="single_right_footer wow fadeIn" data-wow-duration="1.5s">
                                            <ul>
                                                <li><a href=""><i class="lnr lnr-chevron-right"></i> Support</a></li>
                                                <li><a href=""><i class="lnr lnr-chevron-right"></i> Account</a></li>
                                                <li><a href=""><i class="lnr lnr-chevron-right"></i> Product Catalog</a></li>
                                                <li><a href=""><i class="lnr lnr-chevron-right"></i> Shortcodes</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div> 
                        <div class="col-sm-3 col-xs-12">
                            <div class="fo_bottom_socail wow fadeIn" data-wow-duration="2.3s">
                                <a href="#"><i class="fa fa-phone"> 99999999999999</i></a>
                                <a href=""><i class="fa fa-envelope"></i> info@triss.com</a>
                                <p>Pietro Rignanese, Andrea Polenta, Luigi Gurgoglione, Francesco Bocci, Roberto Palloni </p>
                            </div>
                        </div> 
                    </div>
                </div>
				
				
				
				
                
            </div>
        </section><!-- End of footer3 section -->
		
		<footer id="coppyrights" class="coppyrights">
			<div class="container-fluid">
			<div class="row">
				<div class="coppyright">
					<p class="wow fadeInUp" data-wow-duration="2s">Made with <strong>Zend</strong> 2017. All Rights Reserved</p>
				</div>
			</div>
			</div>
		</footer>






        <!-- STRAT SCROLL TO TOP -->

        <div class="scrollup">
            <a href="#"><i class="fa fa-chevron-up"></i></a>
        </div>

    </body>
</html>
