<div class="main_menu_bg navbar-fixed-top">
                <div class="container">
                    <div class="row">
                        <div class="nave_menu wow fadeInUp" data-wow-duration="1s">
                            <nav class="navbar navbar-default" id="navmenu">
                                <div class="container-fluid">
                                    <!-- Brand and toggle get grouped for better mobile display -->
                                    <div class="navbar-header">
                                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                                            <span class="sr-only">Toggle navigation</span>
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                        </button>
                                        <a class="navbar-brand" href=" <?= $this->url(array(	'controller' => 'public',
                                                                                'action'     => 'index',
                                                                                ), 
                                                                        'default',true                   								); 
                                                           ?>"title="Home"><img src="<?php echo $this->baseUrl('../public/images/ic_home.png') ?>" alt=""/></a>
                                    </div>

                                    <!-- Collect the nav links, forms, and other content for toggling -->
                                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                        <ul class="nav navbar-nav navbar-right">
                                            <li><a href=" <?= $this->url(array(	'controller' => 'public',
                                                                                'action'     => 'scelta',
                                                                                ), 
                                                                        'default',true                   								); 
                                                           ?>"title="Registrazione"><img src="<?php echo $this->baseUrl('../public/images/ic_add_user.png') ?>"/></a></li>
                                            <li><a href="#hhh" title="FAQs"><img src="<?php echo $this->baseUrl('../public/images/ic_question_answer.png') ?>"/></a></li>
                     
                                        </ul>
                                    </div>
                                </div>
                            </nav>
                        </div>	
                    </div>

                </div>

            </div>
