<?php echo $this->doctype() ?>
<html>

<head>
	
	<title>ARaynorDesign Template</title>
	
	<?= $this->headMeta();?>
	
    <?= $this->headLink();?>
	
    <?= $this->headTitle();?>
	
    <?= $this->headScript();?>
	
	<?= $this->headScript()
		->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js')
		->appendFile($this->baseUrl('js/vendor/jquery-1.11.2.min.js'))
		->appendFile($this->baseUrl('js/vendor/bootstrap.min.js'))
		->appendFile($this->baseUrl('js/jquery.easypiechart.min.js'))
		->appendFile($this->baseUrl('js/plugins.js'))
		->appendFile($this->baseUrl('js/main.js'))
		->appendFile($this->baseUrl('js/vendor/modernizr-2.8.3-respond-1.4.2.min.js'))
	?>
 
 </head>
    <body data-spy="scroll" data-target="#navmenu">
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
		<div class='preloader'><div class='loaded'>&nbsp;</div></div>
        <!--Home page style-->
        <header id="main_menu" class="header">
			 <?= $this->render('navbar.phtml') ?>
		 </header> <!--End of header -->



        <section id="home" class="home">
            <div class="home-overlay-fluid">
                <div class="container">
                    <div class="row">
                        <div class="main_slider_area">
                            <div class="slider">
                                <div class="single_slider wow fadeIn" data-wow-duration="2s">
                                    <h2>HELLO!</h2>
                                    <p>We love our work...</p>
                                    <p>And We're taking it seriously...</p>
                                </div>
                                <!--<div class="single_slider">
                                    <h2>HELLO!</h2>
                                    <p>We love our work...</p>
                                    <p>And We're taking it seriously...</p>
                                </div>
                                <div class="single_slider">
                                    <h2>HELLO!</h2>
                                    <p>We love our work...</p>
                                    <p>And We're taking it seriously...</p>
                                </div>-->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section><!-- End of Banner Section -->


        <section id="register" class="register">
            <div class="container-fullwidth">
                <div class="row text-center">
                    <div class="col-sm-6 col-xs-6 no-padding">
                        <div class="single_register single_login">
                            <a href="
										<?= $this->url(array(
											'controller' => 'public',
											'action'     => 'login',
											), 
											'default', true);
										?>"
							>Login</a>
                        </div>
                    </div>
                    <div class="col-sm-6 col-xs-6 no-padding">
                        <div class="single_register">
                            <a href="
										<?= $this->url(array(
											'controller' => 'public',
											'action'     => 'registration',
											), 
											'default', true);
										?>">Register</a>
                        </div>
                    </div>
                </div>
            </div>
        </section>


        <!--<section id="domain" class="domainsearce">
            <div class="container">
                <div class="row">
                    <div class="col-sm-10 col-sm-offset-1">
						<div class="main_somainsearrce">
							<div class="head_title text-center wow fadeInDown" data-wow-duration="1s">
								<?//php echo $this->layout()->content; ?>
							</div>
						</div>
					</div>
                </div>
            </div>
        </section>-->


                        <div class="abouts_area">
                            <div class="row">
                                <div class="col-sm-5">
                                    <div class="single_about wow fadeInLeft" data-wow-duration="1.5s">
                                        <h3>About Us</h3>
                                        <p> Descrizione sviluppatori </p>
									</div>
                                </div>
                                <div class="col-sm-7">
                                    <div class="single_about_right wow fadeInRight" data-wow-duration="1.5s">
                                        <div class="row">
                                            <div class="col-sm-4">
                                                <div class="single_team text-center">
                                                    <div class="team_img">
                                                        <img src="../../public/images/team1.jpg" alt="" />
                                                    </div>
                                                    <div class="team_deatels">
                                                        <h4>Jonny Doe</h4>
                                                        <p>Designer</p>
                                                        <div class="team_socail">
                                                            <a href=""><i class="fa fa-facebook"></i></a>
                                                            <a href=""><i class="fa fa-twitter"></i></a>
                                                            <a href=""><i class="fa fa-link"></i></a>
                                                        </div>
                                                    </div>

                                                </div>
                                            </div>
                                            <div class="col-sm-4">
                                                <div class="single_team text-center">
                                                    <div class="team_img">
                                                        <img src="../../../public/images/team3.jpg" alt="" />
                                                    </div>
                                                    <div class="team_deatels">
                                                        <h4>Jonny Doe</h4>
                                                        <p>Designer</p>
                                                        <div class="team_socail">
                                                            <a href=""><i class="fa fa-facebook"></i></a>
                                                            <a href=""><i class="fa fa-twitter"></i></a>
                                                            <a href=""><i class="fa fa-link"></i></a>
                                                        </div>
                                                    </div>

                                                </div>
                                            </div>
                                            <div class="col-sm-4">
                                                <div class="single_team text-center">
                                                    <div class="team_img">
                                                        <img src="../../public/images/team4.jpg" alt="" />
                                                    </div>
                                                    <div class="team_deatels">
                                                        <h4>Jonny Doe</h4>
                                                        <p>Designer</p>
                                                        <div class="team_socail">
                                                            <a href=""><i class="fa fa-facebook"></i></a>
                                                            <a href=""><i class="fa fa-twitter"></i></a>
                                                            <a href=""><i class="fa fa-link"></i></a>
                                                        </div>
                                                    </div>

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>


        <section id="footer" class="footer sections">
            <div class="container">
                <div class="row">
                    <div class="main_footer wow fadeInDown" data-wow-duration="2s">
                        <div class="col-sm-3 col-xs-12">
                            <div class="footer_logo">
                                <a href=""><img src="../../public/images/logo.png" alt="" /></a>
                            </div>
                        </div>
                        <div class="col-sm-9 col-xs-12">
                            <div class="footer_menu">
                                <ul class="list-inline">
                                    <li><a href="">HOME</a></li>
                                    <li><a href="">ABOUT US</a></li>
                                    <li><a href="">BLOG</a></li>
                                    <li><a href="">POLICY</a></li>
                                    <li><a href="">CONTACT</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="footer_bottom_area">
                        <div class="col-sm-9 col-xs-12">
                            <div class="fo_bottom_right">
                                <div class="row">
                                    <div class="col-sm-6 col-xs-12">
                                        <div class="single_right_footer wow fadeIn" data-wow-duration="1s">
                                            <p>Lorem ipsum dolor sit amet, consecteteeseurı adipiscing elit. Donec mollis commodoeesene que, non commodo risus volutpat vel.</p>
                                            <a href="">Design by : <strong>XpeedStudio</strong></a>
											
                                        </div>
                                    </div>
                                    <div class="col-sm-3 col-xs-6">
                                        <div class="single_right_footer wow fadeIn" data-wow-duration="1.5s">
                                            <ul>
                                                <li><a href=""><i class="lnr lnr-chevron-right"></i> Support</a></li>
                                                <li><a href=""><i class="lnr lnr-chevron-right"></i> Account</a></li>
                                                <li><a href=""><i class="lnr lnr-chevron-right"></i> Product Catalog</a></li>
                                                <li><a href=""><i class="lnr lnr-chevron-right"></i> Shortcodes</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="col-sm-3 col-xs-6">
                                        <div class="single_right_footer wow fadeIn" data-wow-duration="2s">
                                            <ul>
                                                <li><a href=""><i class="lnr lnr-chevron-right"></i> Support</a></li>
                                                <li><a href=""><i class="lnr lnr-chevron-right"></i> Account</a></li>
                                                <li><a href=""><i class="lnr lnr-chevron-right"></i> Product Catalog</a></li>
                                                <li><a href=""><i class="lnr lnr-chevron-right"></i> Shortcodes</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div> 
                        <div class="col-sm-3 col-xs-12">
                            <div class="fo_bottom_socail wow fadeIn" data-wow-duration="2.3s">
                                <a href="#"><i class="fa fa-phone"> 0000-0000-0000</i></a>
                                <a href=""><i class="fa fa-envelope"></i> informationteam@ghosthost.com</a>
                                <p>Lorem Ipsum Street, Lorem Avenue,Lorem Ipsum </p>
                            </div>
                        </div> 
                    </div>
                </div>
				
				
				
				
                
            </div>
        </section><!-- End of footer3 section -->
		
		<footer id="coppyrights" class="coppyrights">
			<div class="container-fluid">
			<div class="row">
				<div class="coppyright">
					<p class="wow fadeInUp" data-wow-duration="2s">Made with <strong>...</strong> 2016. All Rights Reserved</p>
				</div>
			</div>
			</div>
		</footer>






        <!-- STRAT SCROLL TO TOP -->

        <div class="scrollup">
            <a href="#"><i class="fa fa-chevron-up"></i></a>
        </div>

    </body>
</html>
